[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_subscription_manager = "GS2MPg4HWgjb3bk6db5x6gBBh3q3oPHxVhRT1VvxKamN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://solana-devnet.g.alchemy.com/v2/RYMgDe1ybfEZrzubzyykgFBqzgx7swnD"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
